### ISSUE TITLE
你好，生成新接口的时候报错

### ISSUE THREAD

**Issue by jacoblai** [zsmhub/wx-channels-sdk#1]
<img width="1399" alt="image" src="https://github.com/zsmhub/wx-channels-sdk/assets/11623139/5cae632b-dd2e-46dd-8c02-8d1bdf05bf6a">

**Comment by zsmhub** [comment]
已处理，拉下最新版本的代码即可 [v1.1.5](https://github.com/zsmhub/wx-channels-sdk/releases/tag/v1.1.5)

**Comment by jacoblai** [comment]
666
