### ISSUE TITLE
参数类型问题

### ISSUE THREAD

**Issue by px94** [zsmhub/wx-channels-sdk#2]
https://github.com/zsmhub/wx-channels-sdk/blob/140ec2c7062a0de91ea761035800126301fdcce6/apis/%E8%AE%A2%E5%8D%95-%E8%8E%B7%E5%8F%96%E8%AE%A2%E5%8D%95%E8%AF%A6%E6%83%85.go#L106

1. 这个文档里面虽然写的是number，看起来定义int没毛病，实际业务中的是string类型的int，截图举例。
2. json解析的时候，本来是一个err可以忽略，除了这个字段整个结构体也能正常解析，但代码偏偏没有返回解析后的结构体，而返回的是一个空结构体。
3. 建议把这个字段改为interface{}
![image](https://github.com/zsmhub/wx-channels-sdk/assets/153472146/e8e63ddd-5710-47b1-9db2-c4fe966bfbe7)

**Comment by zsmhub** [comment]
已改成 string 类型，有问题可以再提哈
